name: Python linting (black, isort, flake8, etc.)

on: [pull_request]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: 'torchsynth'
#          python-root-list: 'torchsynth examples'
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
# For some reason, I get black complaints on github
#          use-black: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: ""
          extra-flake8-options: "--max-line-length=88 --extend-ignore=E203 --per-file-ignores=__init__.py:F401"
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
